module.exports = {
  env: {
    API_URL: process.env.BASE_URL_API,
    NUMBER_TOTAL_PAGINATE_POSTS: process.env.NUMBER_TOTAL_PAGINATE_POSTS,
    NUMBER_TOTAL_PAGINATE_USERS: process.env.NUMBER_TOTAL_PAGINATE_USERS,
    DEFAULT_PAGINATE_POSTS_PAGE: process.env.DEFAULT_PAGINATE_POSTS_PAGE,
    DEFAULT_PAGINATE_USERS_PAGE: process.env.DEFAULT_PAGINATE_USERS_PAGE,
  }
};
