module.exports = {
    env: {
        API_URL: process.env.BASE_URL_API,
        PER_PAGE_USERS_PAGINATE: process.env.PER_PAGE_USERS_PAGINATE,
        DEFAULT_PAGINATE_USERS_PAGE: process.env.DEFAULT_PAGINATE_USERS_PAGE,
        NUMBER_TOTAL_SEARCH_USERS: process.env.NUMBER_TOTAL_SEARCH_USERS,
        PER_PAGE_POSTS_PAGINATE: process.env.PER_PAGE_POSTS_PAGINATE,
        DEFAULT_PAGINATE_POSTS_PAGE_CLIENT: process.env.DEFAULT_PAGINATE_POSTS_PAGE_CLIENT,
        DEFAULT_PAGINATE_POSTS_PAGE_SERVER: process.env.DEFAULT_PAGINATE_POSTS_PAGE_SERVER,
        ONE_PAGE:process.env.ONE_PAGE,
    }
}
